artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/ac848257daed4cb2aba37000893d406e/artifacts
end_time: 1789268803709
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: ac848257daed4cb2aba37000893d406e
run_name: ner_extraction
source_name: ''
source_type: 4
source_version: ''
start_time: 1789268803697
status: 3
tags: []
user_id: divyanshu23
