artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/fb6d272d3b4748ff8a55e3a5afc9394f/artifacts
end_time: 1789269086970
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: fb6d272d3b4748ff8a55e3a5afc9394f
run_name: ner_extraction
source_name: ''
source_type: 4
source_version: ''
start_time: 1789269086958
status: 3
tags: []
user_id: divyanshu23
