artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/669f6bbd3c324694a2e56650cdf9aa84/artifacts
end_time: 1789268888212
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: 669f6bbd3c324694a2e56650cdf9aa84
run_name: ner_extraction
source_name: ''
source_type: 4
source_version: ''
start_time: 1789268888195
status: 3
tags: []
user_id: divyanshu23
