artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/d5c3ffd816fd45929dc13d69d58acb2f/artifacts
end_time: 1789900179464
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: d5c3ffd816fd45929dc13d69d58acb2f
run_name: risk_scoring
source_name: ''
source_type: 4
source_version: ''
start_time: 1789900179451
status: 3
tags: []
user_id: divyanshu23
