artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/15a9c83811af47ab813e8fbac5a3d789/artifacts
end_time: 1789269047548
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: 15a9c83811af47ab813e8fbac5a3d789
run_name: ner_extraction
source_name: ''
source_type: 4
source_version: ''
start_time: 1789269047538
status: 3
tags: []
user_id: divyanshu23
