artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/e58f2fcf43aa4571bc7b4f4d735a1533/artifacts
end_time: 1790282328003
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: e58f2fcf43aa4571bc7b4f4d735a1533
run_name: risk_scoring
source_name: ''
source_type: 4
source_version: ''
start_time: 1790282327995
status: 3
tags: []
user_id: divyanshu23
