artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/ab2471c0d20c4dfd8d48825d952bd7cd/artifacts
end_time: 1789268878298
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: ab2471c0d20c4dfd8d48825d952bd7cd
run_name: ner_extraction
source_name: ''
source_type: 4
source_version: ''
start_time: 1789268878285
status: 3
tags: []
user_id: divyanshu23
