artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/30f954b56e0f480e9584fb71f0bef8a7/artifacts
end_time: 1789268888228
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: 30f954b56e0f480e9584fb71f0bef8a7
run_name: risk_scoring
source_name: ''
source_type: 4
source_version: ''
start_time: 1789268888214
status: 3
tags: []
user_id: divyanshu23
