artifact_uri: /Users/divyanshu23/Downloads/MEDISCRIPT_TRANSFORM/medscript-guard/mlflow_runs/318251182652552263/8c9a5b13a0ab437aadfb90fcf26c7d9e/artifacts
end_time: 1790285076583
entry_point_name: ''
experiment_id: '318251182652552263'
lifecycle_stage: active
run_id: 8c9a5b13a0ab437aadfb90fcf26c7d9e
run_name: risk_scoring
source_name: ''
source_type: 4
source_version: ''
start_time: 1790285076573
status: 3
tags: []
user_id: divyanshu23
